services:
  certificate-authority:
    image: certificate_authority
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certificate-authority
    hostname: ca.localdomain
    ports:
      - 80
      - "2560-2561:2560-2561"
    env_file:
      - .env
    secrets:
      - secret
    restart: always
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
          pids: 32

secrets:
  secret:
    file: .secret
