services:
  nsd:
    image: certificate_authority
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certificate-authority
    hostname: ca.localdomain
    ports:
      - "2560-2561:2560-2561"
    volumes:
      - ./data:/etc/ssl/test:rw
    restart: always
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
          pids: 32
