#!/bin/sh

# 環境の読み出し
if [ -f "$(dirname $0)/.env" ]; then
  source $(dirname $0)/.env
fi

# 設定ファイルのディレクトリ
CONFIG_DIR=${CONFIG_DIR:=.}

# 初期化
dir='/etc/ssl/root_ca'
test -d "$dir"           || mkdir       "$dir"
test -d "$dir/certs"     || mkdir       "$dir/certs"
test -d "$dir/newcerts"  || mkdir       "$dir/newcerts"
test -d "$dir/crl"       || mkdir       "$dir/crl"
test -d "$dir/private"   || mkdir       "$dir/private"
test -f "$dir/serial"    || echo '00' > "$dir/serial"
test -f "$dir/index.txt" || touch       "$dir/index.txt"

# パスフレーズ読み取り
PASSWORD=''
read -s -p "Passphrase: " PASSWORD
echo ''

# 鍵生成
openssl genrsa \
  -batch \
  -passout "pass:${PASSWORD}" \
  -out "$dir/private/private_key.pem" \
  -aes-256-cbc \
  4096

if [ $? -ne 0 ]; then
  echo 'Failed to generate ras key.' > /dev/stderr
  exit 1
fi

# リクエスト
openssl req \
  -batch -new -utf8  \
  -config "${CONFIG_DIR}/openssl.cfg" \
  -section req_RootCA \
  -extensions root_ca \
  -passin "pass:${PASSWORD}" \
  -keyform PEM \
  -key "$dir/private/private_key.pem" \
  -outform PEM \
  -out "$dir/root_ca.csr"

if [ $? -ne 0 ]; then
  echo 'Failed to generate requeset.' > /dev/stderr
  exit 1
fi

# 署名
openssl ca \
  -batch \
  -config "${CONFIG_DIR}/openssl.cfg" \
  -section CA_root \
  -extensions root_ca \
  -md sha256 \
  -in "$dir/root_ca.csr" \
  -passin "pass:${PASSWORD}" \
  -selfsign \
  -cert "$dir/certs/root_ca.crt" \
  -keyform PEM \
  -keyfile "$dir/private/private_key.pem" \
  -days 1825 \
  -out "$dir/certs/root_ca.crt"

if [ $? -ne 0 ]; then
  echo 'Failed to generate certificate.' > /dev/stderr
  exit 1
fi

# 確認
# openssl rsa -noout -text -passin "pass:${PASSWORD}" -in "$dir/private/private_key.pem" 
# openssl x509 -batch -noout -text -in ./root_ca.crt
