#!/bin/sh

# ライブラリ読み出し
source "$(dirname $0)/library.sh"

# 環境の読み出し
if [ -f "$(dirname $0)/.env" ]; then
  source "$(dirname $0)/.env"
fi

# 設定ファイルのディレクトリ
CONFIG_DIR="${CONFIG_DIR:=.}"

# 初期化
ROOT_CA_DIR="${ROOT_CA_DIR:='/etc/ssl/root_ca'}"
INTER_CA_DIR="${INTER_CA_DIR:='/etc/ssl/inter_ca'}"

if [ ! -d "$INTER_CA_DIR" ]; then
  mkdir "$INTER_CA_DIR"
fi
initializeCADir "$INTER_CA_DIR"

# パスフレーズ読み取り
ROOT_CA_PASSWORD=''
readPassword \
  "Input root CA passphrase: " \
  ROOT_CA_PASSWORD

INTER_CA_PASSWORD=''
verifyPassword \
  "Input intermediate CA passphrase: " \
  "Verify intermediate CA passphrase: " \
  INTER_CA_PASSWORD


# 鍵生成
openssl genrsa \
  -batch \
  -passout "pass:$INTER_CA_PASSWORD" \
  -out "$INTER_CA_DIR/private/private_key.pem" \
  -aes-256-cbc \
  4096

if [ $? -ne 0 ]; then
  echo 'Failed to generate ras key.' > /dev/stderr
  exit 1
fi


# リクエスト
openssl req \
  -batch -new -utf8  \
  -config "$CONFIG_DIR/openssl.cfg" \
  -section inter_ca_req \
  -extensions inter_ca \
  -passin "pass:$INTER_CA_PASSWORD" \
  -keyform PEM \
  -key "$INTER_CA_DIR/private/private_key.pem" \
  -outform PEM \
  -out "$INTER_CA_DIR/inter_ca.csr"

if [ $? -ne 0 ]; then
  echo 'Failed to generate requeset.' > /dev/stderr
  exit 1
fi


# 署名
openssl ca \
  -batch \
  -config "$CONFIG_DIR/openssl.cfg" \
  -section CA_inter \
  -extensions inter_ca \
  -md sha256 \
  -in "$INTER_CA_DIR/inter_ca.csr" \
  -passin "pass:$ROOT_CA_PASSWORD" \
  -keyform PEM \
  -keyfile "$ROOT_CA_DIR/private/private_key.pem" \
  -cert "$ROOT_CA_DIR/certs/root_ca.crt" \
  -days 1825 \
  -out "$INTER_CA_DIR/certs/inter_ca.crt"

if [ $? -ne 0 ]; then
  echo 'Failed to generate certificate.' > /dev/stderr
  exit 1
fi


# チェーン生成
openssl crl2pkcs7 \
  -nocrl \
  -certfile "$ROOT_CA_DIR/certs/root_ca.crt" \
  -certfile "$INTER_CA_DIR/certs/inter_ca.crt" \
  -out "$INTER_CA_DIR/certs/ca_chain.p7b"

if [ $? -ne 0 ]; then
  echo 'Failed to generate certificate chain.' > /dev/stderr
  exit 1
fi

# 確認
# openssl x509 -batch -noout -text -in "$dir/certs/inter_ca.crt"
