#!/bin/sh

# ライブラリ読み出し
source "$(dirname $0)/library.sh"

# 環境の読み出し
if [ -f "$(dirname $0)/.env" ]; then
  source "$(dirname $0)/.env"
fi

# 設定ファイルのディレクトリ
CONFIG_DIR="${CONFIG_DIR:=.}"

# パスフレーズ読み取り
ROOT_CA_PASSWORD=''
readPassword \
  "Input root CA passphrase: " \
  ROOT_CA_PASSWORD

INTER_CA_PASSWORD=''
readPassword \
  "Input intermediate CA passphrase: " \
  INTER_CA_PASSWORD

# CRL生成

## ルートCA
openssl ca \
  -batch \
  -gencrl \
  -md sha256 \
  -config "$CONFIG_DIR/openssl.cfg" \
  -section CA_root \
  -extensions root_ca \
  -passin "pass:$ROOT_CA_PASSWORD" \
  -out root_ca.crl

## 中間CA
openssl ca \
  -batch \
  -gencrl \
  -md sha256 \
  -config "$CONFIG_DIR/openssl.cfg" \
  -section CA_inter \
  -extensions inter_ca \
  -passin "pass:$INTER_CA_PASSWORD" \
  -out inter_ca.crl
